Added TOP5 tab
djallberto/presence-analyzer-anowak pull request #13
Opened 2017-04-27 06:40 UTC by djallberto

**JIRA ticket:** [WDP-140](https://kindergarten.stxnext.pl/browse/WDP-140)

2017-04-27 07:07 UTC, djallberto commented on src/presence_analyzer/tests.py
> +                    u'image': '<img src="https://intranet.stxnext.pl/api/images/users/11"/>',
This line is too long but I don't know how to break it correctly

2017-04-28 07:20 UTC, dpolcyn commented on src/presence_analyzer/tests.py
> +        self.assertEqual(data[0], u'September-2013')
u'?

2017-04-28 07:24 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +    months = get_dates()
return get_dates()

2017-05-02 07:30 UTC, piotrgrundas requested changes

2017-05-02 07:30 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +        year = month_year[1]
why not
`month, year = month_year.split('-')`

2017-05-02 07:30 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +            month not in month_name):
style

2017-05-02 07:30 UTC, piotrgrundas commented on src/presence_analyzer/templates/presence_top_5.html
> +            $(document).ready(function() {
`$(function() {` is shorter

2017-05-02 07:30 UTC, piotrgrundas commented on src/presence_analyzer/templates/presence_top_5.html
> +                    var dropdown = $("#object_id");
singleqotes

2017-05-02 07:30 UTC, piotrgrundas commented on src/presence_analyzer/templates/presence_top_5.html
> +                        dropdown.append($("<option />").val(result[item]).text(result[item]));
ditto
and this imo is more readable

    
    $('<option />', {
        'val': result[item],
        'text': result[item]
    })

2017-05-02 07:30 UTC, piotrgrundas commented on src/presence_analyzer/templates/presence_top_5.html
> +                            xhr = null;
indent

2017-05-02 07:30 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +                int(date.year) == int(year)):
style

2017-05-02 07:33 UTC, piotrgrundas requested changes

2017-05-02 07:33 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +        log.debug('{} is not correct format'.format(month_year))
In logging don't use str.format, use `%`
`log.debug(%s xxxx %s, var1, var2)`

2017-05-05 07:27 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +    else:
Is that neccesary?

2017-05-05 07:27 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +    if (len(year) < 4 or
Put this in one line.

2017-05-05 07:31 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +        top_presence[user] = {
use dict comprehension

2017-05-05 11:34 UTC, piotrgrundas requested changes

2017-05-05 11:34 UTC, piotrgrundas commented on src/presence_analyzer/templates/presence_top_5.html
> +                    if (xhr.done()) $dropdown.prop('disabled', false);
never do it in one line
besides
    
    $.getJSON(
        ...
    )
        .done(function () {
            ...
        })

2017-05-05 11:34 UTC, piotrgrundas commented on src/presence_analyzer/templates/presence_top_5.html
> +                            var data = new google.visualization.DataTable(),
indent

2017-05-05 11:34 UTC, piotrgrundas commented on src/presence_analyzer/templates/presence_top_5.html
> +                                    "<img src=\"" + value[1]['image'] + "\"/>",
`$('<img/>', {src: xxx})`

2017-05-05 11:34 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +        self.assertEqual(resp.status_code, 404)
enter

2017-05-05 11:34 UTC, piotrgrundas commented on src/presence_analyzer/tests.py
> +        self.assertEqual(resp.status_code, 200)
enter

2017-05-05 11:34 UTC, piotrgrundas commented on src/presence_analyzer/utils.py
> +            int(date.year) == int(year)):
style

2017-05-05 11:34 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +
?

2017-05-05 11:34 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +        int(user_id)
Why? Check ur route param

2017-05-05 11:34 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +    return top5
Imo there's to much logic here. Such operations should be in some kind of util functions or so. Views should be as light as possible.

2017-05-05 12:23 UTC, djallberto commented on src/presence_analyzer/utils.py
> +            int(date.year) == int(year)):
https://www.python.org/dev/peps/pep-0008/#multiline-if-statements
PEP8 says this is a correct indent
`int()` is incorrect?

2017-05-08 05:30 UTC, dpolcyn commented on src/presence_analyzer/utils.py
> +            int(date.year) == int(year)):
put this to one line

2017-05-08 05:32 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +        } for user in data
for in next line

2017-05-08 05:33 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +    ).items())[:5]
empty line after this

2017-05-08 05:37 UTC, dpolcyn commented on src/presence_analyzer/views.py
> +    data = get_data()
i dont see any reason to get it here

2017-05-08 07:25 UTC, merged