Initial commit
djallberto/presence-analyzer-anowak pull request #9
Opened 2017-04-13 09:22 UTC by djallberto

**JIRA ticket:** [WDP-123](https://kindergarten.stxnext.pl/browse/WDP-123)

2017-04-13 10:00 UTC, piotrgrundas requested changes

2017-04-13 10:00 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +    <title>Presence analyzer</title>
indent

2017-04-13 10:00 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +    return render_template('presence_start_end.html')
1 view which will serv appropriate tpl by param

2017-04-13 10:00 UTC, piotrgrundas commented on src/presence_analyzer/templates/mean_time_weekday.html
> +                <li><a href="{{ url_for('presence_start_end_page') }}">Presence start-end</a></li>
This is repeated, use a loop in which u'll generale `li' and set active page + add it to separate html file and include it It should be included in `base.html`

2017-04-13 10:00 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +    {% block body %}
Many more stuff is repeated in this block, move it out here. This block should contain only stuff which is not repeated.

2017-04-13 10:38 UTC, djallberto commented on src/presence_analyzer/views.py
> +    return render_template('presence_start_end.html')
One extra view to serv tpls or modify mainpage view?

2017-04-13 13:25 UTC, piotrgrundas requested changes

2017-04-13 13:25 UTC, piotrgrundas commented on src/presence_analyzer/templates/header.html
> +            <li id="selected">
just add class instead of whole li

2017-04-13 13:25 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +        {% endblock %}
`{% block body %}{% endblock %}`
Imo content is more appropriate name

2017-04-13 13:25 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +</html>
</body>
    </html>

2017-04-13 13:25 UTC, piotrgrundas commented on src/presence_analyzer/views.py
> +    )
What if some1 will pass wrong template?

2017-04-14 06:47 UTC, djallberto commented on src/presence_analyzer/templates/base.html
> +        {% endblock %}
I named it body, because it was in body block. But now it should be named `content`, right

2017-04-14 09:34 UTC, piotrgrundas requested changes

2017-04-14 09:34 UTC, piotrgrundas commented on src/presence_analyzer/templates/nav.html
> +    {% endfor %}
indent

2017-04-14 09:34 UTC, piotrgrundas commented on src/presence_analyzer/templates/presence_weekday.html
> +    </div>
This block repeats across all templates, only `<h2>` differs

2017-04-14 09:53 UTC, piotrgrundas requested changes

2017-04-14 09:53 UTC, piotrgrundas commented on src/presence_analyzer/templates/presence_weekday.html
> +{% endblock %}
Don't u think that this is more like heading rather then content?

2017-04-14 10:00 UTC, djallberto commented on src/presence_analyzer/templates/presence_weekday.html
> +{% endblock %}
Yeah, but this block extends `content` div. I tend to name blocks as their parents which they relate to. But I agree that here it should be named `{% block header %}`

2017-04-14 10:07 UTC, piotrgrundas requested changes

2017-04-14 10:07 UTC, piotrgrundas commented on src/presence_analyzer/templates/base.html
> +
remove

2017-04-14 10:10 UTC, merged